# Site settings
title: Copilot can do that?
email: burkeholland@gmail.com
description: Magical things you can do with GitHub Copilot
baseurl: "" 
url: "http://copilotcandothat.com" # the base hostname & protocol for your site, e.g. http://example.com

# Exclude from processing.
exclude:
  - node_modules

collections:
  tips:
    output: true
    permalink: /tips/:path